version: 2

builds:
  - main: .
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    binary: yd-dl-{{ .Os }}-{{ .Arch }}

archives:
  - format: binary
    name_template: "{{ .Binary }}"

checksum:
  disable: true

release:
  github:
    owner: hyperpuncher
    name: yd-dl
